<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Carshow.Utilities\Carshow.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Backend\MohammadWork\CarShow\CarShow.ApplicationService.Contract\IService\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Backend\MohammadWork\CarShow\CarShow.ApplicationService.Contract\IService\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
